### ISSUE TITLE
Some contacts get shown multiple times

### ISSUE THREAD

**Issue by toddy15** [rigid/Birthdroid#18] opened 2015-10-15 08:13 UTC
Maybe there's something wrong with my contacts database, but I get some contacts displayed three times. HOwever, other apps which use and show the contact data do not have this problem. Therefore, I've added an easy fix to filter out multiple contact results.

**Comment by rigid** [comment] 2015-10-19 10:13
strange, I hope that's not caused by Birthdroid itself. Could it be, that you store contacts twice? On your phone/sim/google/cloud etc... Which android version?
The fix makes sense, but I could imagine, it's not enough. The contacts could be different when not synced. Maybe it's better to "merge" doubles by checking the contacts name properties.
I'll look into it, as soon as possible.
An anonymised logcat of the problem would be helpful if you can provide one.

**Comment by rigid** [comment] 2015-12-25 12:44
i'm 99% sure that you have multiple addressbooks with unmerged contacts. (can you confirm this?)
I created #20 to tackle this. Closing this issue, feel free to re-open if you think i'm wrong.

**Closed by rigid** 2015-12-25 12:44 UTC
